### PR TITLE
Support of multiple Riak versions. Each cluster may be created with it is own version of Riak.

### PR DESCRIPTION
**Pull request by platon**

### CODE REVIEW

**Comment by sanmiguel** [comment]
Exciting!

**Comment by sanmiguel** [comment]
Related: https://github.com/basho-labs/riak-mesos-tools/pull/56

**Comment by sanmiguel** [comment]
This (and the tools PR) are looking great so far!

**Comment by platon** [comment]
@sanmiguel I added small fix for riak-versions API call. For now it shows config riak urls except artifact urls.

**Comment by sanmiguel** [comment]
Thanks for this @platon - looking great!

**Pull request merged**
